/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wDBqFJDKTHt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function CheckoutForm() {
  return (
    <div className="container mx-auto px-4 py-8 md:py-12">
      <div className="grid grid-cols-1 md:grid-cols-[2fr_1fr] gap-8">
        <div className="border rounded-lg p-6">
          <h2 className="text-2xl font-bold mb-4">Корзина</h2>
          <div className="space-y-4">
            <div className="grid grid-cols-[80px_1fr_80px] items-center gap-4">
              <img
                alt="Товар 1"
                className="rounded-md"
                height={80}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "80/80",
                  objectFit: "cover",
                }}
                width={80}
              />
              <div>
                <h3 className="font-medium">Товар 1</h3>
                <p className="text-gray-500">Описание товара</p>
              </div>
              <div className="flex items-center gap-2">
                <Button size="icon" variant="outline">
                  <MinusIcon className="w-4 h-4" />
                </Button>
                <span>1</span>
                <Button size="icon" variant="outline">
                  <PlusIcon className="w-4 h-4" />
                </Button>
              </div>
              <div className="font-medium">$19.99</div>
            </div>
            <div className="grid grid-cols-[80px_1fr_80px] items-center gap-4">
              <img
                alt="Товар 2"
                className="rounded-md"
                height={80}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "80/80",
                  objectFit: "cover",
                }}
                width={80}
              />
              <div>
                <h3 className="font-medium">Товар 2</h3>
                <p className="text-gray-500">Описание товара</p>
              </div>
              <div className="flex items-center gap-2">
                <Button size="icon" variant="outline">
                  <MinusIcon className="w-4 h-4" />
                </Button>
                <span>2</span>
                <Button size="icon" variant="outline">
                  <PlusIcon className="w-4 h-4" />
                </Button>
              </div>
              <div className="font-medium">$29.99</div>
            </div>
          </div>
        </div>
        <div className="border rounded-lg p-6">
          <h2 className="text-2xl font-bold mb-4">Оформление заказа</h2>
          <form className="space-y-4">
            <div className="grid gap-2">
              <Label htmlFor="name">Имя</Label>
              <Input id="name" placeholder="Введите имя" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" placeholder="Введите email" type="email" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="address">Адрес</Label>
              <Textarea id="address" placeholder="Введите адрес" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="phone">Телефон</Label>
              <Input id="phone" placeholder="Введите телефон" type="tel" />
            </div>
            <Button className="w-full" type="submit">
              Оформить заказ
            </Button>
          </form>
        </div>
      </div>
    </div>
  )
}

function MinusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
